kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"
  disableDefaultCNI: true
  apiServerPort: 6443
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  networking:
    serviceSubnet: "10.96.0.1/12"
    podSubnet: "10.240.0.0/16"
  apiVersion: v1
nodes:
- role: control-plane
- role: control-plane
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
  - containerPort: 443
    hostPort: 443
  - containerPort: 2222
    hostPort: 2222
  extraMounts:
  - hostPath: /usr/src
    containerPath: /usr/src
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 8081
  - containerPort: 443
    hostPort: 444
  - containerPort: 2222
    hostPort: 2223
  extraMounts:
  - hostPath: /usr/src
    containerPath: /usr/src
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 8082
  - containerPort: 443
    hostPort: 445
  - containerPort: 2222
    hostPort: 2224
  extraMounts:
  - hostPath: /usr/src
    containerPath: /usr/src

